FROM nginxinc/nginx-unprivileged:1.27-alpine

USER root
RUN apk upgrade --no-cache
USER 101

COPY index.html /usr/share/nginx/html/index.html
COPY style.css /usr/share/nginx/html/style.css
COPY app.js /usr/share/nginx/html/app.js
COPY nginx.k8s.conf /etc/nginx/conf.d/default.conf

COPY --chmod=755 docker-entrypoint.d/40-generate-server-info.sh /docker-entrypoint.d/40-generate-server-info.sh

EXPOSE 8080
