apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: cluster-chronicles
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: cluster-chronicles
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /prometheus
    prometheus.io/port: "3000"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: backend
  ports:
    - name: http
      port: 3000
      targetPort: http
