input {
  beats { port => 5044 }
}

filter {
  if [application][service] {
    mutate { add_field => { "[@metadata][target_index]" => "application-logs-%{+YYYY.MM.dd}" } }
  } else if [log_category] == "docker" {
    mutate { add_field => { "[@metadata][target_index]" => "docker-logs-%{+YYYY.MM.dd}" } }
  } else {
    mutate { add_field => { "[@metadata][target_index]" => "system-logs-%{+YYYY.MM.dd}" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][target_index]}"
  }
  stdout { codec => rubydebug }
}
