global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: node
    static_configs:
      - targets:
          - 192.168.56.10:9100
          - 192.168.56.11:9100
          - 192.168.56.12:9100
          - 192.168.56.13:9100
          - 192.168.56.14:9100
      - targets:
          - host.docker.internal:9100
        labels:
          instance: 192.168.56.15:9100

  - job_name: cadvisor
    static_configs:
      - targets:
          - 192.168.56.11:8081
          - 192.168.56.12:8081
          - 192.168.56.13:8081
          - 192.168.56.14:8081
          - 192.168.56.15:8081

  - job_name: application
    metrics_path: /prometheus
    static_configs:
      - targets: ["192.168.56.13:3000"]

  - job_name: elasticsearch
    static_configs:
      - targets: ["elasticsearch-exporter:9114"]
