---
- name: Deploy backend
  hosts: app
  become: true
  roles:
    - backend

- name: Deploy frontend
  hosts: web
  become: true
  roles:
    - frontend

- name: Configure load balancer
  hosts: loadbalancer
  become: true
  roles:
    - loadbalancer