[loadbalancer]
lb-01 ansible_host=192.168.56.10 ansible_ssh_private_key_file={{ssh_key_dir}}/lb-01

[web]
web-01 ansible_host=192.168.56.11 ansible_ssh_private_key_file={{ssh_key_dir}}/web-01
web-02 ansible_host=192.168.56.12 ansible_ssh_private_key_file={{ssh_key_dir}}/web-02

[app]
app-01 ansible_host=192.168.56.13 ansible_ssh_private_key_file={{ssh_key_dir}}/app-01

[cicd]
ci-01 ansible_host=192.168.56.14 ansible_ssh_private_key_file={{ssh_key_dir}}/ci-01

[monitoring]
monitoring-01 ansible_host=192.168.56.15 ansible_ssh_private_key_file={{ssh_key_dir}}/monitoring-01

[docker_hosts:children]
web
app
cicd
monitoring

[observed_hosts:children]
loadbalancer
web
app
cicd
monitoring

[all:vars]
ansible_user=devops
ssh_key_dir=/home/joalausi/.ssh/automation-alchemy
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
