apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../manifests/namespaces
  - ../../manifests/storage
  - ../../manifests/security
  - ../../manifests/backend
  - ../../manifests/frontend
  - ../../manifests/ci-cd
  - ../../manifests/monitoring
  - ../../manifests/logging
  - ../../manifests/ingress
labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
